# примеры API-запросов

@baseUrl = http://localhost:8000/api
###
# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP87777",
  "description": "Датчик в ванной222"

}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/2/
Content-Type: application/json

{
  "name": "DS22",
  "description": "yyy"



}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 11
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/2/
Content-Type: application/json
