# примеры API-запросов

@baseUrl = http://localhost:8000/api
###
# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP8777",
  "description": "Датчик в ванной11"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/2/
Content-Type: application/json

{
  "name": "Задолбал снова",
  "description": "Убрал"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 14,
  "temperature": 33
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/14/
Content-Type: application/json
