# примеры API-запросов

@baseUrl = http://localhost:8000/api
###
# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP8777",
  "description": "Датчик в ванной12"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/2/
Content-Type: application/json

{
  "description": "Снова поставил"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/2/
Content-Type: application/json
